python -u .\Retest_SPAN.py --k 5 --index 0 --round 0
python -u .\Retest_SPAN.py --k 5 --index 1 --round 0
python -u .\Retest_SPAN.py --k 5 --index 2 --round 0
python -u .\Retest_SPAN.py --k 5 --index 3 --round 0
python -u .\Retest_SPAN.py --k 5 --index 4 --round 0
python -u .\Retest_SPAN.py --k 5 --index 0 --round 1
python -u .\Retest_SPAN.py --k 5 --index 1 --round 1
python -u .\Retest_SPAN.py --k 5 --index 2 --round 1
python -u .\Retest_SPAN.py --k 5 --index 3 --round 1
python -u .\Retest_SPAN.py --k 5 --index 4 --round 1
python -u .\Retest_SPAN.py --k 5 --index 0 --round 2
python -u .\Retest_SPAN.py --k 5 --index 1 --round 2
python -u .\Retest_SPAN.py --k 5 --index 2 --round 2
python -u .\Retest_SPAN.py --k 5 --index 3 --round 2
python -u .\Retest_SPAN.py --k 5 --index 4 --round 2
python -u .\Retest_SPAN.py --k 5 --index 0 --round 3
python -u .\Retest_SPAN.py --k 5 --index 1 --round 3
python -u .\Retest_SPAN.py --k 5 --index 2 --round 3
python -u .\Retest_SPAN.py --k 5 --index 3 --round 3
python -u .\Retest_SPAN.py --k 5 --index 4 --round 3
python -u .\Retest_SPAN.py --k 5 --index 0 --round 4
python -u .\Retest_SPAN.py --k 5 --index 1 --round 4
python -u .\Retest_SPAN.py --k 5 --index 2 --round 4
python -u .\Retest_SPAN.py --k 5 --index 3 --round 4
python -u .\Retest_SPAN.py --k 5 --index 4 --round 4
python -u .\Retest_SPAN.py --k 5 --index 0 --round 5
python -u .\Retest_SPAN.py --k 5 --index 1 --round 5
python -u .\Retest_SPAN.py --k 5 --index 2 --round 5
python -u .\Retest_SPAN.py --k 5 --index 3 --round 5
python -u .\Retest_SPAN.py --k 5 --index 4 --round 5
python -u .\Retest_SPAN.py --k 5 --index 0 --round 6
python -u .\Retest_SPAN.py --k 5 --index 1 --round 6
python -u .\Retest_SPAN.py --k 5 --index 2 --round 6
python -u .\Retest_SPAN.py --k 5 --index 3 --round 6
python -u .\Retest_SPAN.py --k 5 --index 4 --round 6
python -u .\Retest_SPAN.py --k 5 --index 0 --round 7
python -u .\Retest_SPAN.py --k 5 --index 1 --round 7
python -u .\Retest_SPAN.py --k 5 --index 2 --round 7
python -u .\Retest_SPAN.py --k 5 --index 3 --round 7
python -u .\Retest_SPAN.py --k 5 --index 4 --round 7
python -u .\Retest_SPAN.py --k 5 --index 0 --round 8
python -u .\Retest_SPAN.py --k 5 --index 1 --round 8
python -u .\Retest_SPAN.py --k 5 --index 2 --round 8
python -u .\Retest_SPAN.py --k 5 --index 3 --round 8
python -u .\Retest_SPAN.py --k 5 --index 4 --round 8
python -u .\Retest_SPAN.py --k 5 --index 0 --round 9
python -u .\Retest_SPAN.py --k 5 --index 1 --round 9
python -u .\Retest_SPAN.py --k 5 --index 2 --round 9
python -u .\Retest_SPAN.py --k 5 --index 3 --round 9
python -u .\Retest_SPAN.py --k 5 --index 4 --round 9
